### ISSUE TITLE
JSON with external attributes

### ISSUE THREAD

**Issue by kevin4dhd** [flutterdata/flutter_data_json_api_adapter#1]
Hello, it's me again, sorry for so many questions, I wanted to know how I can manipulate this json, I got here reading the documentation and I already saw the source code of flutter_data_json_api_adapter.dart, with that I have solved the data part ["docs"] , But how do I make the object also return the pages and items? In the case of a list of users, I no longer want it to return a list of users, but an object with all those parameters (inside the list, pages and items), I'm thinking of creating a parent object that inherits those two attributes plus docs, but I don't want to create a class for every object it creates, and it wouldn't make sense when I get only one object, if you could give me an idea of how solve it I would be very grateful

![image](https://user-images.githubusercontent.com/22886367/102882237-152d5e80-441c-11eb-93de-f68acd9c444e.png)

**Comment by frank06** [comment]
Sorry, this is not compliant [JSON:API](https://jsonapi.org)
