### ISSUE TITLE
Force unwrapping empty map to remove the id is causing a crash/error

### ISSUE THREAD

**Issue by GabrielAraujo** [flutterdata/flutter_data_json_api_adapter#2]
Hey!

When we try to call a repository to make a request with an empty object it is crashing when the `flutter_data_json_api_datapter.dart` line 77 tries to remove the `id` attribute from an empty map.

We use this just to make a plain POST method call.

```
    _latestEntry.value = await repo.save(TimeEntry(), params: {
      'xxx': xxx,
    });
```

**Comment by frank06** [comment]
Was fixed in https://github.com/flutterdata/flutter_data_json_api_adapter/commit/a6064c421ed640de1d762da35f743698d2e04835
